sfPaymentDoctrineStorage:
  columns:
    reference:
      type: string(50)
      primary: true
      notnull: true
    type:
      type: string(20)
      primary: true
      notnull: true
    date:
      type: timestamp
      notnull: true
    status:
      type: string(15)
      notnull: true
    vendor:
      type: string(100)
      notnull: true
    buyer:
      type: string(100)
      notnull: true
    total_amount:
      type: string(20)
    params:
      type: clob
      notnull: true